from scrapy import cmdline
# cmdline.execute("scrapy crawl jxwmw_spider -o jxwmw.csv".split())
# cmdline.execute("scrapy crawl netease_news_spider -o neteaseHit.csv".split())
# cmdline.execute("scrapy crawl sina_news_spider -o sinaHit.csv".split())
# cmdline.execute("scrapy crawl sohu_news_spider -o sohu.csv".split())
# cmdline.execute("scrapy crawl xinhua_news_spider -o xinhua.csvifeng".split())
# cmdline.execute("scrapy crawl ifeng_news_spider -o .csv".split())
# cmdline.execute("scrapy crawl cctv_news_spider -o cctv.csv".split())
# cmdline.execute("scrapy crawl jndsb_news_spider -o jndsb.csv".split())
# cmdline.execute("scrapy crawl tencent_news_spider -o tencentHit.csv".split())
# cmdline.execute("scrapy crawl jxcn_news_spider -o jxcn.csv".split())
cmdline.execute("scrapy crawl people_news_spider -o peopleHit.csv".split())
# cmdline.execute("scrapy crawl chinanews_spider -o chinanews.csv".split())
# cmdline.execute("scrapy crawl weather_spider -o weather.csv".split())
# cmdline.execute("scrapy crawl jxnews_spider -o jxnews.csv".split())
# cmdline.execute("scrapy crawl jxcbw_news_spider -o jxcbw.csv".split())
# cmdline.execute("scrapy crawl xinmin_news_spider -o xinminHit.csv".split())
# cmdline.execute("scrapy crawl zgqxb_news_spider -o xinqixiangHit.csv".split())

